- sigpy/mri/samp.py
Update radial golden angle increment to 111.25 degrees, as originally proposed in: Winkelmann, S. et al., An Optimal Radial Profile Order Based on the Golden Ratio for Time-Resolved MRI, IEEE TMI, 2007
> update radial golden angle increment to 111.25 degrees

- sigpy/app.py
In linear least squares if x is initialized x_device does not get updated correctly.
> Update to fix device placement in LinearLeastSquares

- sigpy/__init__.py
- sigpy/config.py
- sigpy/plot.py
- sigpy/pytorch.py
- tests/test_pytorch.py
- Add functions to perform zero-copy conversion between between numpy/cupy arrays and Pytorch tensor.
- Add a function to convert SigPy Linop to a PyTorch function.
For complex arrays with shape `s`, the corresponding output PyTorch tensor has shape `s + [2]`, where the first channel represents real, and the second channel represents imaginary.
The converted PyTorch function behaves like a native PyTorch function with zero additional copying. It can be back propagated, and applied on GPU tensors.
> Pytorch interop

- README.rst
- requirements.txt
- sigpy/conv.py
- sigpy/linop.py
- sigpy/mri/linop.py
- tests/test_conv.py
- tests/test_linop.py
Support strides in convolution functions.
Combine input/output multi_channel options to one option.
Use scipy.signal.convolve for CPU which selects fastest method instead of only fft_convolve.
Move to CPU and use scipy convolution when cudnn is not enabled.
> Strided convolution

- sigpy/linop.py
The adjoint operator for NUFFTAdjoint should be the NUFFT operator.
> Fix NUFFTAdjoint operator

- sigpy/linop.py
- sigpy/wavelet.py
This implements fwt and iwt using xp functions to enable GPU wavelet. The implementation directly tiles the decomposition coefficients in a manner similar to PyWavelet's coeffs_to_array. This allows the new implementation to be used as a drop-in replacement. I have tested it with ```wshfl.py``` (https://github.com/sidward/pywshfl) and the speed is now comparable to BART. Please let me know if you need me to make any changes.
> Reimplement wavelet using xp functions.

- sigpy/fourier.py
- sigpy/interp.py
- sigpy/linop.py
- sigpy/mri/dcf.py
- tests/test_interp.py
- tests/test_linop.py
The old version of interpolate and gridding used a discretized array to specify the kernel. Linear interpolation was then used to compute continuous interpolation weights from the array. This introduces errors and is not intuitive to use. For example, both [1, 0] and [1, 0.5, 0] specify linear interpolation.
The new version accepts the kernel name as argument and evaluate the kernel function internally. In particular, the functions implement `spline` and `kaiser_bessel` kernels. In addition, a `param` argument is added to specify kernel parameters. For `spline`, it specifies the order, and for `kaiser_bessel`, it specifies the beta parameter. In particular, `spline` with `param=1` performs linear interpolation.
> Restructure interpolation

- sigpy/linop.py
The current argument to Circshift will cause xp.roll to be called multiple extra times, with a shift of 0. This causes a slight decrease in speed. I have pasted a script that compares the current and the new implementation.
```python
import numpy as np
import sigpy as sp
from sigpy import util
from sigpy.linop import Identity, Circshift, Reshape, Vstack
def FiniteDifference(ishape, axes=None):
"""Linear operator that computes finite difference gradient.
Args:
ishape (tuple of ints): Input shape.
axes (tuple or list): Axes to circularly shift. All axes are used if
None.
"""
I = Identity(ishape)
ndim = len(ishape)
axes = util._normalize_axes(axes, ndim)
linops = []
for i in axes:
D = I - Circshift(ishape, [1], axes=[i])
R = Reshape([1] + list(ishape), ishape)
linops.append(R * D)
G = …
```
> Improved FiniteDifference by removing unnecessary calls over extra axes

- sigpy/thresh.py
- sigpy/util.py
My other solution to the problem described in https://github.com/mikgroup/sigpy/pull/41 turned out to be not very robust. I was beginning to need to make too many changes to several other parts of the repo involving scalars. Changing the Python scalar to CuPy scalar array right before the ElementwiseKernel is simplest solution for now. A repo-wide change to scalars can be made later if desired.
The following code should show errors before merging my changes. And after merging, they should be gone.
```python
import traceback
import sigpy as sp
from sigpy import util
device = 2
arr_shape = (24, 256, 512)
device = sp.Device(device)
xp = device.xp
with device:
x = util.randn(arr_shape, dtype=xp.complex64, device=device)
y = util.randn(arr_shape, dtype=xp.complex64, device=device)
a = 2.4  # a …
```
> Fixed scalars being wrong input to ElementwiseKernels

- sigpy/mri/samp.py
In the poisson func:  the output variable that represents the density was changed - now the func returns R instead of r. That's because the inner function (_poisson) uses R for generating samples of rad.
> poisson func output variable change

- sigpy/mri/samp.py
- tests/mri/test_samp.py
Fixed #57 
Instead of using `numpy.random.RandomState` to preserve the numpy state, which isn't supported with numba, we save and restore the numpy state with `numpy.random.{get,set}_state`
> Fix Numba/numpy.random.RandomState incompatibility

- sigpy/mri/app.py
I found a memory leak in the ESPIRiT calibration app. When it's finished and dereferenced, it still uses some memory on GPU. I tracked down the problem to a reference to the ESPIRiT app that is passed to the PowerMethod alg.
The following code shows that there is memory that remains allocated even when the ESPIRiT app is done and no longer referenced.
```python
import numpy as np
import cupy as cp
import sigpy as sp
from sigpy.mri.app import EspiritCalib
def my_function():
device = sp.Device(0)
ksp = sp.util.randn((4, 128, 128, 128), dtype=np.complex64, device=device)
app = EspiritCalib(ksp, device=device)
mps = app.run()
return
def print_mem():
with cp.cuda.Device(0):
mempool = cp.get_default_memory_pool()
used = mempool.used_bytes() / 1024 / 1024
total = mempool.total_bytes() / 1024 / …
```
> Fix memory leak caused by alg referencing app object

- sigpy/mri/app.py
- sigpy/mri/dcf.py
- sigpy/mri/linop.py
This change allows users to specify image shape instead of relying on `estimate_shape`, which may produce shapes that aren't what the user expects. The option to specify image shape has been added to `JsenseRecon` and `pipe_menon_dcf`.
However, the `estimate_shape` function is still being used to estimate `grd_shape` in three places (all related to JSENSE):
https://github.com/mikgroup/sigpy/blob/8c25c53a15b99643be7adcdc351f7ba55fcea649/sigpy/mri/app.py#L314
https://github.com/mikgroup/sigpy/blob/8c25c53a15b99643be7adcdc351f7ba55fcea649/sigpy/mri/linop.py#L122
https://github.com/mikgroup/sigpy/blob/8c25c53a15b99643be7adcdc351f7ba55fcea649/sigpy/mri/linop.py#L160
I'm not so familiar with the shapes that are required here, whether it is important that `grd_shape` is a certain shape, so I …
> Add option to specify img_shape

- docs/mri_rf.rst
- sigpy/config.py
- sigpy/mri/rf/trajgrad.py
- tests/mri/rf/test_trajgrad.py
- tests/test_pytorch.py
This is to add a python version of Miki's arc length based gradient calculations. There are also some minor changes to pytorch import and testing. Since the prebuilt pytorch versions are linked to their own cudnn this can be in conflict with the cudnn from condaforge (e.g. 8.05 (broken on condaforge) vs 8.1). If you import pytorch first this is fixed for now.
> Add min time gradient code for arbitrary trajectories. 

- sigpy/block.py
- sigpy/linop.py
1. Without casting, an error is thrown if a tuple is used in the ArrayToBlocks or BlocksToArray linop.
2. The linop dimensions weren't being assigned correctly when the input had more than 3 dims.
> Fixes to BlocksToArray and ArrayToBlocks

- sigpy/config.py
This PR makes cupy more of an optional dependency in sigpy. When cupy import fails, sigpy raises a warning, instead of an error. This allows sigpy to continue operating without cupy being available.
This scenario is difficult to simulate via unittests. However, it was verified in the case below:
Scenario:`machineA` has gpu, `machineB` does not have gpu. Both machines share a single NAS filesystem.
1. Conda environment created using machineA on shared NAS. This environment is also visible to machineB
2. `import sigpy` works on machineA - this is expected and was happening before.
3. `import sigpy` also works on machineB, even though gpu is not available on machineB
Resolves #77
> update config.py to treat cupy as an optional dependency

- sigpy/mri/rf/trajgrad.py
This makes the behaviour consistent with Michael Lustig's code.
cc: @kmjohnson3
> Correct default value for gfin in min_time_gradient

- .travis.yml
- requirements.txt
- sigpy/mri/linop.py
- tests/mri/test_app.py
- tests/mri/test_linop.py
Fix: When using coil_batch_size, SENSE linop stacked coil sensitivity maps interleavedly, which does not work properly for coil_batch_size > 1. Now, SENSE linop stacks them successively.
Test: Modified function in test_app (test_shepp_logan_SenseRecon) and modified two in test_linop (test_sense_model_batch and test_noncart_sense_model_batch) for coil_batch_size >= 1.
> Fix SENSE linop to work with coil_batch_size > 1

- sigpy/config.py
> try/except protection to warn for cudnn_enabled

- sigpy/alg.py
- sigpy/app.py
- sigpy/mri/samp.py
- sigpy/mri/sim.py
- sigpy/mri/util.py
- sigpy/sim.py
- sigpy/util.py
- tests/learn/test_app.py
- tests/mri/test_app.py
- tests/mri/test_linop.py
- tests/mri/test_precond.py
- tests/test_alg.py
- tests/test_fourier.py
- tests/test_linop.py
- tests/test_pytorch.py
- tests/test_util.py
This changes all instances of 
np.complex -> complex
np.float -> float
np.bool -> bool
np.int -> int
as they are depcreated since numpy 1.20.
Closes #123.
> Remove deprecated type specifiers

- sigpy/alg.py
- sigpy/mri/rf/slr.py
- sigpy/mri/rf/trajgrad.py
- tests/test_version.py
As described in #142, several changes in the scipy and numpy packages lead to errors in sigpy. 
I tried to fix them so that all tests pass now, but I am not a sigpy user myself and can't guarantee that all changes in the function calls, especially the introduction of the kwarg "weight", are actually correct. Would be great if someone could confirm that the one character variable `w` is supposed to be a `weight` (although from the scipy changelog I am quite sure that this is the case 😁 )
The rest should be fine. 
closes #142
> Fix incompatibility with scipy 1.14.0 and numpy 2.0
